-- Seed data for attributes
-- Run with: psql -f supabase/seeds/01_attributes.sql

-- Equipment
INSERT INTO attributes (name, slug, category, icon) VALUES
-- Cardio Equipment
('Treadmills', 'treadmills', 'equipment', NULL),
('Ellipticals', 'ellipticals', 'equipment', NULL),
('Stationary Bikes', 'stationary-bikes', 'equipment', NULL),
('Rowing Machines', 'rowing-machines', 'equipment', NULL),
('Stair Climbers', 'stair-climbers', 'equipment', NULL),
('Assault Bikes', 'assault-bikes', 'equipment', NULL),
('Ski Ergs', 'ski-ergs', 'equipment', NULL),
('Jacob''s Ladder', 'jacobs-ladder', 'equipment', NULL),

-- Strength Equipment
('Squat Racks', 'squat-racks', 'equipment', NULL),
('Power Racks', 'power-racks', 'equipment', NULL),
('Deadlift Platforms', 'deadlift-platforms', 'equipment', NULL),
('Olympic Lifting Platforms', 'olympic-lifting-platforms', 'equipment', NULL),
('Bench Press Stations', 'bench-press-stations', 'equipment', NULL),
('Smith Machines', 'smith-machines', 'equipment', NULL),
('Cable Machines', 'cable-machines', 'equipment', NULL),
('Lat Pulldown Machines', 'lat-pulldown-machines', 'equipment', NULL),
('Leg Press Machines', 'leg-press-machines', 'equipment', NULL),
('Hack Squat Machines', 'hack-squat-machines', 'equipment', NULL),
('Leg Curl Machines', 'leg-curl-machines', 'equipment', NULL),
('Leg Extension Machines', 'leg-extension-machines', 'equipment', NULL),
('Chest Press Machines', 'chest-press-machines', 'equipment', NULL),
('Shoulder Press Machines', 'shoulder-press-machines', 'equipment', NULL),
('Seated Row Machines', 'seated-row-machines', 'equipment', NULL),
('Pec Deck Machines', 'pec-deck-machines', 'equipment', NULL),
('Glute Machines', 'glute-machines', 'equipment', NULL),
('Hip Abductor/Adductor', 'hip-abductor-adductor', 'equipment', NULL),
('Calf Raise Machines', 'calf-raise-machines', 'equipment', NULL),

-- Free Weights
('Dumbbells', 'dumbbells', 'equipment', NULL),
('Barbells', 'barbells', 'equipment', NULL),
('Olympic Barbells', 'olympic-barbells', 'equipment', NULL),
('EZ Curl Bars', 'ez-curl-bars', 'equipment', NULL),
('Trap Bars', 'trap-bars', 'equipment', NULL),
('Kettlebells', 'kettlebells', 'equipment', NULL),
('Weight Plates', 'weight-plates', 'equipment', NULL),
('Bumper Plates', 'bumper-plates', 'equipment', NULL),
('Medicine Balls', 'medicine-balls', 'equipment', NULL),
('Slam Balls', 'slam-balls', 'equipment', NULL),
('Battle Ropes', 'battle-ropes', 'equipment', NULL),
('Sandbags', 'sandbags', 'equipment', NULL),

-- Functional Training
('Pull-Up Bars', 'pull-up-bars', 'equipment', NULL),
('Dip Stations', 'dip-stations', 'equipment', NULL),
('Plyo Boxes', 'plyo-boxes', 'equipment', NULL),
('TRX Suspension Trainers', 'trx-suspension-trainers', 'equipment', NULL),
('Resistance Bands', 'resistance-bands', 'equipment', NULL),
('Foam Rollers', 'foam-rollers', 'equipment', NULL),
('Ab Wheels', 'ab-wheels', 'equipment', NULL),
('GHD Machines', 'ghd-machines', 'equipment', NULL),
('Climbing Ropes', 'climbing-ropes', 'equipment', NULL),
('Sleds', 'sleds', 'equipment', NULL),
('Prowlers', 'prowlers', 'equipment', NULL),
('Yoke', 'yoke', 'equipment', NULL),
('Farmers Walk Handles', 'farmers-walk-handles', 'equipment', NULL),
('Atlas Stones', 'atlas-stones', 'equipment', NULL),
('Log Press', 'log-press', 'equipment', NULL)
ON CONFLICT (slug) DO NOTHING;

-- Amenities
INSERT INTO attributes (name, slug, category, icon) VALUES
('Locker Rooms', 'locker-rooms', 'amenity', NULL),
('Showers', 'showers', 'amenity', NULL),
('Towel Service', 'towel-service', 'amenity', NULL),
('Sauna', 'sauna', 'amenity', NULL),
('Steam Room', 'steam-room', 'amenity', NULL),
('Hot Tub', 'hot-tub', 'amenity', NULL),
('Swimming Pool', 'swimming-pool', 'amenity', NULL),
('Basketball Court', 'basketball-court', 'amenity', NULL),
('Racquetball Courts', 'racquetball-courts', 'amenity', NULL),
('Tennis Courts', 'tennis-courts', 'amenity', NULL),
('Indoor Track', 'indoor-track', 'amenity', NULL),
('Outdoor Area', 'outdoor-area', 'amenity', NULL),
('Stretching Area', 'stretching-area', 'amenity', NULL),
('Turf Area', 'turf-area', 'amenity', NULL),
('Free Parking', 'free-parking', 'amenity', NULL),
('Valet Parking', 'valet-parking', 'amenity', NULL),
('Bike Storage', 'bike-storage', 'amenity', NULL),
('Childcare', 'childcare', 'amenity', NULL),
('Kids Area', 'kids-area', 'amenity', NULL),
('Juice Bar', 'juice-bar', 'amenity', NULL),
('Cafe', 'cafe', 'amenity', NULL),
('Vending Machines', 'vending-machines', 'amenity', NULL),
('Pro Shop', 'pro-shop', 'amenity', NULL),
('Supplement Sales', 'supplement-sales', 'amenity', NULL),
('WiFi', 'wifi', 'amenity', NULL),
('TV Screens', 'tv-screens', 'amenity', NULL),
('Air Conditioning', 'air-conditioning', 'amenity', NULL),
('24/7 Access', '24-7-access', 'amenity', NULL),
('Staffed Hours', 'staffed-hours', 'amenity', NULL),
('Personal Training Available', 'personal-training-available', 'amenity', NULL),
('Group Classes Included', 'group-classes-included', 'amenity', NULL),
('Guest Passes', 'guest-passes', 'amenity', NULL),
('Day Passes Available', 'day-passes-available', 'amenity', NULL),
('Month-to-Month Options', 'month-to-month-options', 'amenity', NULL),
('No Contract Required', 'no-contract-required', 'amenity', NULL),
('Student Discount', 'student-discount', 'amenity', NULL),
('Senior Discount', 'senior-discount', 'amenity', NULL),
('Military Discount', 'military-discount', 'amenity', NULL),
('Corporate Memberships', 'corporate-memberships', 'amenity', NULL)
ON CONFLICT (slug) DO NOTHING;

-- Classes
INSERT INTO attributes (name, slug, category, icon) VALUES
('Yoga', 'yoga', 'class', NULL),
('Hot Yoga', 'hot-yoga', 'class', NULL),
('Pilates', 'pilates', 'class', NULL),
('Spin/Cycling', 'spin-cycling', 'class', NULL),
('HIIT', 'hiit', 'class', NULL),
('Boot Camp', 'boot-camp', 'class', NULL),
('CrossFit Classes', 'crossfit-classes', 'class', NULL),
('Boxing', 'boxing', 'class', NULL),
('Kickboxing', 'kickboxing', 'class', NULL),
('Martial Arts', 'martial-arts', 'class', NULL),
('Brazilian Jiu-Jitsu', 'brazilian-jiu-jitsu', 'class', NULL),
('MMA', 'mma', 'class', NULL),
('Zumba', 'zumba', 'class', NULL),
('Dance Fitness', 'dance-fitness', 'class', NULL),
('Barre', 'barre', 'class', NULL),
('Strength Training Classes', 'strength-training-classes', 'class', NULL),
('Circuit Training', 'circuit-training', 'class', NULL),
('Aqua Fitness', 'aqua-fitness', 'class', NULL),
('Senior Fitness', 'senior-fitness', 'class', NULL),
('Prenatal Fitness', 'prenatal-fitness', 'class', NULL),
('Kids Classes', 'kids-classes', 'class', NULL),
('Meditation', 'meditation', 'class', NULL),
('Stretching Classes', 'stretching-classes', 'class', NULL),
('Functional Training Classes', 'functional-training-classes', 'class', NULL),
('Olympic Lifting Classes', 'olympic-lifting-classes', 'class', NULL),
('Powerlifting Classes', 'powerlifting-classes', 'class', NULL),
('Strongman Classes', 'strongman-classes', 'class', NULL)
ON CONFLICT (slug) DO NOTHING;

-- Specialties
INSERT INTO attributes (name, slug, category, icon) VALUES
('Powerlifting', 'powerlifting', 'specialty', NULL),
('Olympic Weightlifting', 'olympic-weightlifting', 'specialty', NULL),
('Bodybuilding', 'bodybuilding', 'specialty', NULL),
('CrossFit', 'crossfit', 'specialty', NULL),
('Strongman', 'strongman', 'specialty', NULL),
('Functional Fitness', 'functional-fitness', 'specialty', NULL),
('Sports Performance', 'sports-performance', 'specialty', NULL),
('Weight Loss', 'weight-loss', 'specialty', NULL),
('Senior Fitness', 'senior-fitness-specialty', 'specialty', NULL),
('Rehabilitation', 'rehabilitation', 'specialty', NULL),
('Physical Therapy', 'physical-therapy', 'specialty', NULL),
('Pre/Post Natal', 'pre-post-natal', 'specialty', NULL),
('Youth Training', 'youth-training', 'specialty', NULL),
('Women''s Only', 'womens-only', 'specialty', NULL),
('Competition Prep', 'competition-prep', 'specialty', NULL),
('Nutrition Coaching', 'nutrition-coaching', 'specialty', NULL),
('Online Coaching', 'online-coaching', 'specialty', NULL)
ON CONFLICT (slug) DO NOTHING;

-- Recovery
INSERT INTO attributes (name, slug, category, icon) VALUES
('Massage Therapy', 'massage-therapy', 'recovery', NULL),
('Sports Massage', 'sports-massage', 'recovery', NULL),
('Foam Rolling Area', 'foam-rolling-area', 'recovery', NULL),
('Stretching Area', 'stretching-area-recovery', 'recovery', NULL),
('Cold Plunge', 'cold-plunge', 'recovery', NULL),
('Ice Bath', 'ice-bath', 'recovery', NULL),
('Cryotherapy', 'cryotherapy', 'recovery', NULL),
('Infrared Sauna', 'infrared-sauna', 'recovery', NULL),
('Compression Therapy', 'compression-therapy', 'recovery', NULL),
('Normatec Boots', 'normatec-boots', 'recovery', NULL),
('Percussion Therapy', 'percussion-therapy', 'recovery', NULL),
('Theragun/Hypervolt', 'theragun-hypervolt', 'recovery', NULL),
('Red Light Therapy', 'red-light-therapy', 'recovery', NULL),
('Float Tank', 'float-tank', 'recovery', NULL),
('Chiropractic', 'chiropractic', 'recovery', NULL),
('Physical Therapy On-Site', 'physical-therapy-on-site', 'recovery', NULL),
('Sports Medicine', 'sports-medicine', 'recovery', NULL)
ON CONFLICT (slug) DO NOTHING;
